(setq package-enable-at-startup nil)
(add-to-list 'initial-frame-alist '(background-color . "#1e1e2e"))
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq gc-cons-threshold (* 50 1000 1000))
(setq read-process-output-max (* 1024 1024))
