(setq package-enable-at-startup nil)
(add-to-list 'initial-frame-alist '(background-color . "#1e1e2e"))
(when (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(setq gc-cons-threshold (* 50 1000 1000))
(setq read-process-output-max (* 1024 1024))
(setq site-run-file nil)
(setq load-prefer-newer t)
